# fly.toml app configuration file generated for tailwind-remix-run-blues-starter-blog on 2023-06-29T18:25:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tailwind-remix-run-mdxjs-typescript-starter-blog"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bash ./scripts/migrate.sh"

[env]
  METRICS_PORT = "8081"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

[metrics]
  port = 8081
  path = "/metrics"
